[tool.poetry]
name = "csw"
version = "1.3.2"
description = "Catalogue service for spatial records over HTTP in the Department of Biodiversity, Conservation and Attractions."
authors = ["ASU <asu@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
django = "3.2.19"
psycopg2 = "2.9.4"
django-extensions = "3.2.1"
python-dotenv = "1.0.0"
dbca-utils = "1.1.6"
dj-database-url = "1.0.0"
gunicorn = "20.1.0"
django-reversion = "4.0.2"
whitenoise = {version = "6.3.0", extras = ["brotli"]}
lxml = "4.9.1"
pycsw = "2.6.1"
pyproj = "3.4.1"
sqlalchemy = "1.4.46"
djangorestframework = "3.11.2"
django-filter = "22.1"
mixer = "6.1.3"
requests = "2.28.2"
click = "8.1.3"

[tool.poetry.group.dev.dependencies]
ipython = "^8.10.0"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry>=1.2.2"]
build-backend = "poetry.masonry.api"
