apiVersion: apps/v1
kind: Deployment
metadata:
  name: csw-deployment
  labels:
    app: csw-uat
spec:
  selector:
    matchLabels:
      app: csw-uat
  template:
    metadata:
      labels:
        app: csw-uat
    spec:
      containers:
      - name: csw
        image: ghcr.io/dbca-wa/csw
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: csw-env-uat
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: csw-env-uat
              key: SECRET_KEY
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: csw-env-uat
              key: BASE_URL
        - name: CORS_URL
          valueFrom:
            secretKeyRef:
              name: csw-env-uat
              key: CORS_URL
        - name: AZURE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: csw-env-uat
              key: AZURE_ACCOUNT_NAME
        - name: AZURE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: csw-env-uat
              key: AZURE_ACCOUNT_KEY
        - name: AZURE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: csw-env-uat
              key: AZURE_CONTAINER
