apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
secretGenerator:
  - name: csw-env
    type: Opaque
    envs:
      - .env
resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/dbca-wa/csw
    newTag: 1.3.9
patches:
  - path: deployment_patch.yaml
  - path: service_patch.yaml
